version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3338:3338"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "8080:8080"